### ISSUE TITLE
Add support for enable-access-log

### ISSUE THREAD

**Issue by alnvdl-work** [canonical/nginx-ingress-integrator-operator#111]
### Enhancement Proposal

For charms of applications that generate a lot of logs, disabling access logs with `enable-access-log: false` helps save significant amounts of storage. This is especially relevant if the application is already logging the requests it's receiving. We have some examples of this internally in Canonical.

**Comment by weiiwang01** [comment]
I think this option is for the ingress controller and it will disable logging for the entire ingress controller? If so, I think this might be better managed by the cluster system administrator rather than being managed at the charm level.

**Comment by weiiwang01** [comment]
@alnvdl-work that's right, sorry I misread the configuration. I agree this is a very good addition to the `nginx-ingress-integrator`!

**Comment by alnvdl-work** [comment]
@weiiwang01 Is there a timeline for this being available? We depend on this for deploying some of our services that receive a lot of traffic.

**Comment by weiiwang01** [comment]
> @weiiwang01 Is there a timeline for this being available? We depend on this for deploying some of our services that receive a lot of traffic.

@alnvdl-work Sorry, I have added it in this pull request: https://github.com/canonical/nginx-ingress-integrator-operator/pull/121 I will make it merged and released soon.

**Comment by weiiwang01** [comment]
Revision 91 released adding the option `enable-access-log`.
