### ISSUE TITLE
ingress url missing from relation databag of the ingress/v2 relation 

### ISSUE THREAD

**Issue by Thanhphan1147** [canonical/nginx-ingress-integrator-operator#119]
### Bug Description

Hello, I just have a looked at https://github.com/canonical/charm-relation-interfaces/tree/main/interfaces/ingress/v2 that defines the ingress relation and it seems that the charm current doesn't put this information in its application databag.  

### To Reproduce
I deployed a charm that supports the `ingress` relation together with `nginx-ingress-integrator`
```
juju deploy jenkins-k8s --channel=latest/edge
juju deploy nginx-ingress-integrator --channel=v2/edge --revision=82 --config service-hostname=jenkins-k8s --config path-routes=/ --trust
juju relate jenkins-k8s:ingress nginx-ingress-integrator
```

After that, when inspecting the relation databag (e.g using `jhack show-relation`), I was expecting to find 
```
application_data: {
  ingress: '{"url": "http://jenkins-k8s"}'
}
```
in the application databag of the `nginx-ingress-integrator` charm. However this does not seem to be the case at the moment

### Environment

```
$ juju --version
3.1.7-genericlinux-amd64
```

### Relevant log output

```shell
$ juju exec --unit jenkins-k8s/0 "relation-get -r ingress:0 - nginx-ingress-integrator"
{}
```

**Comment by mthaddon** [comment]
This was fixed in https://github.com/canonical/nginx-ingress-integrator-operator/pull/126
