### ISSUE TITLE
Typo in a tutorial command

### ISSUE THREAD

**Issue by goulinkh** [canonical/nginx-ingress-integrator-operator#159]
### Bug Description

The docs page: https://charmhub.io/nginx-ingress-integrator/docs/secure-an-ingress-with-tls
This command should be in lowercase in order to work using copy/paste:
Current:
```
OpenSSL genrsa -out ca.key 2048
```
Expected:
```
openssl genrsa -out ca.key 2048
```

### To Reproduce

N/A

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by cbartz** [comment]
Thanks. Updated.
