### ISSUE TITLE
Add Backend Protocol Config Option

### ISSUE THREAD

**Issue by kelkawi-a** [canonical/nginx-ingress-integrator-operator#59]
### Enhancement Proposal

Hi,

It would be useful to have a config option to set the [backend protocol](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol) (e.g. to GRPC) on each resource created by the charm. A charm could be related to multiple other charms, so should offer the ability of setting different backend protocols for each relation.

**Comment by weiiwang01** [comment]
Thank you for your suggestion! This seems to be not very difficult to implement.

But I just have one concern: will this option conflict with other options in the Nginx ingress integrator charm? For example, `tls-secret-name` or `owasp-modsecurity-crs`.

**Comment by kelkawi-a** [comment]
I'm not well-versed in the different annotations for the ingress resource so I'm not sure. Is there a reason to believe they might conflict? Currently I am manually editing the ingress resource to include `nginx.ingress.kubernetes.io/backend-protocol: GRPC`.

**Comment by weiiwang01** [comment]
For example, if the `owasp-modsecurity-crs` charm configuration is set to be `true`. The `nginx.ingress.kubernetes.io/enable-modsecurity: true` and `nginx.ingress.kubernetes.io/enable-owasp-modsecurity-crs: true` annotations will be added to the ingress resources. Could the `nginx.ingress.kubernetes.io/enable-modsecurity:true` annotation coexists with `nginx.ingress.kubernetes.io/backend-protocol: GRPC` on the same ingress resources?

**Comment by weiiwang01** [comment]
I have added this new feature to our roadmap, thank you for your suggestion!

**Comment by amandahla** [comment]
Fixed by https://github.com/canonical/nginx-ingress-integrator-operator/pull/66
