### ISSUE TITLE
Ability to whitelist IPs for specific paths

### ISSUE THREAD

**Issue by kian99** [canonical/nginx-ingress-integrator-operator#78]
### Enhancement Proposal

Hi, 

I'm trying to figure out if I'm be able to coerce the current nginx-ingress charm to provide IP whitelisting for specific paths using the `whitelist-source-range` and `path-routes` config options. With pure Kubernetes this seems possible as described [here](https://stackoverflow.com/questions/58925853/kubernetes-ingress-whitelist-ip-for-path).

**Motivation:**
This would be useful to gate certain endpoints, e.g. a `/admin` endpoint behind a VPN, preventing users from ever getting to the application layer.

**Experimentation:**
I've so far been unsuccessful in trying to achieve this. The link above suggests creating 2 ingress resources, one that includes the ip whitelist for the `/admin` endpoint and a second that is the ingress for all other endpoints and according to kubernetes [docs](https://juju.is/docs/olm/deployment-of-juju-agents) the longer path would take precedence which would all work out. 

I've tried making two relations from my application to a single nginx-ingress charm as well as deploying 2 nginx charms, in both cases ensuring that the requiring charm provides different service names and relation names as seen below.

```python
        require_nginx_route(
            charm=self,
            service_hostname=self.config["external_hostname"],
            service_name=f"{self.app.name}_all",
            service_port=8080,
            nginx_route_relation_name="ingress-route"
        )
        require_nginx_route(
            charm=self,
            service_hostname=self.config["external_hostname"],
            service_name=f"{self.app.name}_admin",
            service_port=8080,
            path_routes="/admin",
            nginx_route_relation_name="admin-route"
        )
```
The main problem seems to be [this bit](https://github.com/canonical/nginx-ingress-integrator-operator/blob/main/src/charm.py#L209) from the source where it states,
>If there are 2 or more services configured to use the same service-hostname, the controller nginx/nginx-ingress requires them to be in the same Kubernetes Ingress object. Otherwise, Ingress will be served for only one of the services. Because of this, we'll have to group all ingresses into the same Kubernetes Resource based on their requested service-hostname.

This seems to stand at odds with the stackoverflow answer above and the reason its an issue is because when I set the `whitelist-source-range`, the annotation is added to the entire ingress, thereby gating the whole service instead of just a specific endpoint. I've also confirmed looking at the generated nginx config using `microk8s kubectl exec -n ingress nginx-ingress-microk8s-controller-gnj6s -- cat /etc/nginx/nginx.conf` that the config contains two routes but both restrict access to the IPs specified in `whitelist-source-range`.

So using the charm I can't create two separate ingress objects with the same host address which is what I think I'm after.

**Comment by weiiwang01** [comment]
Yes, I think this is a bug.

If two relations are connected to one `nginx-ingress-integrator`, the ingress integrator will try to merge ingresses with the same hosts.

And if two relation each connects to their own `nginx-ingress-integrator`. Since the ingress integrator update the resources by name, for configuration described above, the generated resource names are the same for the two relations. So the ingress integrator will have some problem updating seperately.

Thanks for reporting this issue, we will fix this soon and limit the ingress integrator to only accept one relation to avoid the ambiguity of the situation like this.

**Comment by kian99** [comment]
Hi @weiiwang01 just bumping this thread to check if there is any estimated timeline on when this might get addressed? No rush or anything what my team currently plan to do is just manually create the ingress.yaml and `kubectl apply` it.

**Comment by weiiwang01** [comment]
> Hi @weiiwang01 just bumping this thread to check if there is any estimated timeline on when this might get addressed? No rush or anything what my team currently plan to do is just manually create the ingress.yaml and `kubectl apply` it.

Hi @kian99 , the pull request for that is already ready https://github.com/canonical/nginx-ingress-integrator-operator/pulls. But as it's quite a lot of changes, it takes some time to review, merge and release this version. I think it should be done in one or two weeks.

**Comment by pandrey2003** [comment]
Dear team, any updates on the introduction of the functionality outlined by Kian? I see the PR was closed, and now we need this feature for the new Contracts service. Thanks in advance!

**Comment by weiiwang01** [comment]
> Dear team, any updates on the introduction of the functionality outlined by Kian? I see the PR was closed, and now we need this feature for the new Contracts service. Thanks in advance!

Hi @pandrey2003, For the latest version of nginx-ingress-integrator, you should be able to deploy two nginx-ingress-integrator applications, each relating to one of the relation endpoints. This should enable you to apply different configurations to the two different ingress resources. Please let me know if there are any problems related to this approach, and if everything is fine, I will close this issue. Thank you.

**Comment by pandrey2003** [comment]
Hey @weiiwang01, yes, that works! I wonder if we could do the same via one ingress unit instead of two, but the current way also works.

**Comment by weiiwang01** [comment]
> Hey @weiiwang01, yes, that works! I wonder if we could do the same via one ingress unit instead of two, but the current way also works.

It's recommended to use one nginx-ingress-integrator charm per relation, as this greatly reduces the ambiguity of configuration options. For higher versions of the nginx-ingress-integrator charm, it is mandatory to have one nginx-ingress-integrator charm per relation. There's very little overhead in deploying multiple nginx-ingress-integrator charms since the charm is workload-less; it will mostly be idle and consume very few resources after deployment.

**Comment by pandrey2003** [comment]
We use the charm inside of the Terraform plan ... so we do not call the Python code, but rather define the integrations declaratively. Is there a way to use the Terraform plan and have only one integration? I can show you the code in direct messages, given this particular usage is for an internal project, thanks.

**Comment by weiiwang01** [comment]
> We use the charm inside of the Terraform plan ... so we do not call the Python code, but rather define the integrations declaratively. Is there a way to use the Terraform plan and have only one integration? I can show you the code in direct messages, given this particular usage is for an internal project, thanks.

Hey @pandrey2003, sorry I missed your reply. I am not sure which charm you are planning to deploy, but use charm described in this issue's body as an example. It's possible to use Terraform to deploy two integrations together. Here's what it probably looks like (untested). I am not sure if this satisfies your needs and feel free to contact me if you have any additional questions about this.

```terraform
resource "juju_application" "nginx_ingress_integration_admin_route" {
  name  = "nginx-ingress-integration-admin-route"
  model = "model-name"
  charm {
    name     = "nginx-ingress-integrator"
    revision = 101
    channel  = "latest/stable"
  }
}

resource "juju_application" "nginx_ingress_integration_ingress_route" {
  name  = "nginx-ingress-integration-ingress-route"
  model = "model-name"
  charm {
    name     = "nginx-ingress-integrator"
    revision = 101
    channel  = "latest/stable"
  }
}

resource "juju_application" "your_application" {
  name  = "your-application"
  model = "model-name"
  charm {
    name     = "your-application"
    revision = 123
    channel  = "latest/stable"
  }
}

resource "juju_integration" "admin_route" {
  model = "model-name"

  application {
    name     = juju_application.nginx_ingress_integration_admin_route.name
    endpoint = "nginx-route"
  }

  application {
    name = juju_application.your_application.name
    endpoint = "admin-route"
  }
}

resource "juju_integration" "ingress_route" {
  model = "model-name"

  application {
    name     = juju_application.nginx_ingress_integration_ingress_route.name
    endpoint = "nginx-route"
  }

  application {
    name = juju_application.your_application.name
    endpoint = "ingress-route"
  }
}
```

**Comment by pandrey2003** [comment]
Yep, this is what we are doing now :)
