### ISSUE TITLE
ExternalName ingress route support

### ISSUE THREAD

**Issue by claudiubelu** [canonical/nginx-ingress-integrator-operator#93]
### Enhancement Proposal

Kubernetes has a Service type ``ExternalName`` (https://kubernetes.io/docs/concepts/services-networking/service/#externalname), which allows the Cluster DNS Service to return a CNAME record to the set ``externalName``. This can be useful in certain situations, such as creating a ingress routes for a github page (https://pages.github.com/).

The ``nginx-ingress-integrator`` does not have any support for this at this moment. The charm has no config options for this. As for charms related to it, the charm creates ``ClusterIP`` services and references them in the ``ingress`` objects it creates. Because the charm itself creates the ``ClusterIP`` service used for Ingress, we can't simply develop another workload-less charm that would define the ``ExternalName`` Service and relate it to the ``nginx-ingress-integrator`` charm and have it use it in the ingress definition.

For addressing this, there are few solutions:

- Add an ``external-name`` config option and relation data field. Setting this would imply that the Service type will be ``ExternalName``. The charm would then create the Kubernetes service with that type, and set the appropiate ``externalName`` field in its spec. The downside for this: Let's say that we'd want ``foo.lish.com/`` to point towards some github pages, however we already have an ``nginx-ingress-integrator`` charm related to our application charm (for ``foo.lish.com/bar``). This means that we can't configure the same charm to create the ``ExternalName``, as the config options override the relation data and do not represent a separate entity. We can't simply deploy a second ``nginx-ingress-integrator`` charm and configure that with the ``externalName`` and the same ``service-hostname`` as we can't have 2 ``nginx-ingress-integrator`` charms manage the same Ingress resource, and we can't have 2 separate Ingress resources with the same hosts (not all NGINX Ingress Controllers supports this). A solution for this would be to create a skeleton charm, which basically only has the ingress relation and configures it.

- Add CRUD actions for ingress routes.

**Comment by weiiwang01** [comment]
Another problem is that I think the external name requires the `nginx.ingress.kubernetes.io/backend-protocol` set to `HTTPS` on the ingress resources to forward HTTPS traffic. This setting could conflict with other services connected to the ingress.

Another potential solution is the `nginx.ingress.kubernetes.io/server-snippet`. This allows you to inject arbitrary Nginx configurations into the Nginx ingress controller configuration. You could potentially inject configurations like `location /foobar { proxy_pass https://pages.github.com/; }` to the `nginx.ingress.kubernetes.io/server-snippet`. However, this is untested, and I'm not sure if it's possible.

**Comment by cbartz** [comment]
@weiiwang01 Can you follow-up here, please?

**Comment by amandahla** [comment]
@weiiwang01 friendly ping

**Comment by weiiwang01** [comment]
I am leaning towards the conclusion that this is unlikely to be implemented. I will close this issue for now, but we can reopen it in the future if there is demand.
